### ISSUE TITLE
[BUG]: what's up with ther kernel panic

### ISSUE THREAD

**Issue by juniorohanyere** [EthernalRaine/SkylightOS#25]
**Describe the bug**
A kernel panic

**To Reproduce**
```bash
qemu-system-x86_64 -kernel publish/sysroot/boot/ekernel.elf
```
or from the iso image
```bash
qemu-system-x86_64 -cdrom publish/skylight.iso 
```
**Expected behavior**
Expected to load the kernel, but I got kernel panic

**Screenshots (if possible)**
![Screenshot_2023-07-17_10_09_43](https://github.com/EthernalRaine/SkylightOS/assets/106378800/91ee303d-18c4-4a92-8e59-aeb5e20ea6f0)

**OS Version**
Linux localhost 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali1 (2023-02-20) x86_64 GNU/Linux

**Additional context**

**Comment by ghost** [comment]
not really a bug, the kernel panic is intentionally done with the kernel code. nothing else other than that is really implemented, anyway.
see the "_esaul_kernel_entry" function in src/base/esos/ekernel.c, that's where it does the kernel panic.

**Comment by juniorohanyere** [comment]
Ok, thanks @pinksub , I got that
